### PR TITLE
chore: update azure dependencies

### PR DESCRIPTION
**Pull request by roeap**
This PR bumps the azure dependencies to latest.

Most notably the error handling in the azure SDKs improved significantly.

### CODE REVIEW

**Comment by roeap** [comment]
currently CI is failing due to an issue in the Azure SDKs Azure/azure-sdk-for-rust#823

**Comment by tustvold** [comment]
I rebased this, but there still appears to be an upstream issue

**Comment by roeap** [comment]
Agreed, having a more focused implementation for communicating with the different APIs contained in this repo would be great! I even thought about getting this started here for azure, as I have a fairly good grasp about the azure APIs... the main thing stopping me from this is authorization. I guess when this is based on keys, some form of hmac (as mentioned in the description of #18 is all that is needed). However in almost all my applications we have to move to identitity based access, sometimes based on managed identities. My hope would therefore be that we can support oauth flows or provide some kind of token provider trait that we can implement externally to support these scenarios.

**Comment by roeap** [comment]
@alamb - this PR is currently blocked by a bug in the azure crates, which leads to ci failures. The bug is already fixed and we are waiting for a release. In can ask over there when that would be. I also plan to contribute an implementation of #18 for azure. I guess getting this one in would be nice to have, but should not block donating the crate. The work on the implementation using no azure dependencies should then happen in its new home. If we migrate before this one I would likely not re-open but go directly for #18.

**Comment by alamb** [comment]
👍 Thanks @roeap 

We can simply wait to see what the schedule is -- and I am happy to help port this PR to a new repo if needed

**Comment by alamb** [comment]
The archiving of this crate is imminent -- see https://github.com/influxdata/object_store_rs/pull/52

@roeap  shall we try and port this PR to arrow-rs so that it doesn't get lost? I am happy to help

**Comment by roeap** [comment]
@alamb - I thinks It's a good idea to take port this over. Was hoping to g directly for a local implementation, but not sure yet when I'll get to this. Should be able to get this done this weekend. I will also ping the people in the azure sdk again, to release the fixes so we can get this merged into arrow-rs repo.

**Pull request closed without merging**
